version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-svc
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - APP_ENV=dev
      - DB_DSN=postgres://postgres:postgres@postgres:5432/tasks?sslmode=disable
      - HTTP_ADDR=:8080
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: task-svc-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
